apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springweb-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/conceptit/springdemo-config.git
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
      - values/development.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: springweb
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

